### PR TITLE
Overengineer

### PR DESCRIPTION
**Pull request by t-richards**
- [x] Fancy new overengineered version
 - [x] Ultimately a ripoff of the original work by @lancepioch 
 - [x] Split things into multiple files
 - [x] Adds asset preprocessing via `gulp` and friends
 - [x] Net gain of 62 lines of "code"
 - [x] JavaScript => CoffeeScript, CSS => Less

# Before

```bash
$ cloc .
       3 text files.
       3 unique files.                              
       1 file ignored.

http://cloc.sourceforge.net v 1.62  T=0.02 s (134.9 files/s, 12230.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              1             26              0            143
Javascript                       1              8              0             48
HTML                             1              4              0             43
-------------------------------------------------------------------------------
SUM:                             3             38              0            234
-------------------------------------------------------------------------------
```

# After

```bash
$ cloc .
      18 text files.
      18 unique files.                              
       7 files ignored.

http://cloc.sourceforge.net v 1.62  T=0.05 s (267.5 files/s, 7180.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1              5              6            119
CoffeeScript                     6             14              5             73
LESS                             4             17              6             63
JSON                             1              0              0             29
Handlebars                       1              0              0             12
-------------------------------------------------------------------------------
SUM:                            13             36             17            296
-------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by t-richards** [comment]
@lancepioch requested preserving the "show-only-online-streamers" idea from the previous version, IIRC.

**Comment by lancepioch** [comment]
:+1:  for license

- [ ] Remove Gulp
- [ ] Remove Bootstrap
- [ ] Either locally host font-awesome or CDNJS it

**Comment by t-richards** [comment]
>Remove Bootstrap
For what reason? It's currently powering the nice grid/responsive/dropdown nav elements and I'd rather not have a DIY-solution.

>Either locally host font-awesome or CDNJS it
The `gulp:copy` task takes the appropriate files from `node_modules` and places them in the `web` directory (`gulp` is intended to be run on deploy).

**Comment by lancepioch** [comment]
Never mind about the Bootstrap, I was thinking of a different solution, but now I agree with it.

**Pull request merged**
